Configuration.o: Configuration.cc Configuration.h
DictionariesMenu.o: DictionariesMenu.cc DictionariesMenu.h Utils.h \
  config.h
ErrorHandlers.o: ErrorHandlers.cc ErrorHandlers.h config.h
HelperPanel.o: HelperPanel.cc HelperPanel.h
IndicatorWidget.o: IndicatorWidget.cc IndicatorWidget.h
main.o: main.cc MainWindow.h Toolbar.h PoReader.h TextPanel.h \
  TranslatedTextPanel.h TranslateTxtView.h IndicatorWidget.h \
  Configuration.h
MainWindow.o: MainWindow.cc MainWindow.h Toolbar.h PoReader.h TextPanel.h \
  TranslatedTextPanel.h TranslateTxtView.h IndicatorWidget.h MenuBar.h \
  Configuration.h HelperPanel.h config.h
MenuBar.o: MenuBar.cc MenuBar.h
PoReader.o: PoReader.cc PoReader.h Utils.h ErrorHandlers.h config.h
Statistics.o: Statistics.cc Statistics.h
test_replace.o: test_replace.cc Utils.h
TextPanel.o: TextPanel.cc TextPanel.h TranslateTxtView.h
Toolbar.o: Toolbar.cc Toolbar.h PoReader.h DictionariesMenu.h config.h
TranslatedTextPanel.o: TranslatedTextPanel.cc TranslatedTextPanel.h \
  TranslateTxtView.h IndicatorWidget.h config.h
TranslateTxtView.o: TranslateTxtView.cc TranslateTxtView.h config.h
Utils.o: Utils.cc Utils.h
