Configuration.o: Configuration.cc Configuration.h
HelperPanel.o: HelperPanel.cc HelperPanel.h
IndicatorWidget.o: IndicatorWidget.cc IndicatorWidget.h
main.o: main.cc MainWindow.h Toolbar.h PoReader.h TextPanel.h \
  Configuration.h
MainWindow.o: MainWindow.cc MainWindow.h Toolbar.h PoReader.h TextPanel.h \
  Utils.h MenuBar.h Configuration.h TranslatedTextPanel.h \
  TranslateTxtView.h IndicatorWidget.h HelperPanel.h config.h
MenuBar.o: MenuBar.cc MenuBar.h
PoReader.o: PoReader.cc PoReader.h config.h
TextPanel.o: TextPanel.cc TextPanel.h TranslateTxtView.h
Toolbar.o: Toolbar.cc Toolbar.h PoReader.h
TranslatedTextPanel.o: TranslatedTextPanel.cc TranslatedTextPanel.h \
  TranslateTxtView.h IndicatorWidget.h config.h
TranslateTxtView.o: TranslateTxtView.cc TranslateTxtView.h
Utils.o: Utils.cc Utils.h
